language: go

services:
  - mysql
  - redis

go:
  - 1.2
  - 1.3
  - release
#  - tip

install:
  - go get code.google.com/p/go.tools/cmd/vet || true
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/tools/godep
  - $HOME/gopath/bin/godep restore ./...

script: go vet ./... && go test ./... -race -v

before_script:
  - export TT=`date -u +%H%M%S`
  - export PAYMENTD_MYSQLTEST=true
  - export PAYMENTD_MYSQLTEST_PRINCIPALDSN="root@tcp(localhost:3306)/paymentd_test_principal_$TT?charset=utf8mb4&parseTime=true&loc=UTC&timeout=1m&wait_timeout=30&interactive_timeout=30&time_zone=%22%2B00%3A00%22"
  - export PAYMENTD_MYSQLTEST_PAYMENTDSN="root@tcp(localhost:3306)/paymentd_test_payment_$TT?charset=utf8mb4&parseTime=true&loc=UTC&timeout=1m&wait_timeout=30&interactive_timeout=30&time_zone=%22%2B00%3A00%22"
  - mysql -u root -e "create database if not exists paymentd_test_principal_$TT;"
  - mysql -u root -e "create database if not exists paymentd_test_payment_$TT;"
  - mysql -u root -D paymentd_test_principal_$TT < ./resources/mysql/paymentd.test.principal.sql
  - mysql -u root -D paymentd_test_payment_$TT < ./resources/mysql/paymentd.test.payment.sql
  - mysql -u root -D paymentd_test_principal_$TT < ./resources/mysql/paymentd.test.principal.data.sql
  - mysql -u root -D paymentd_test_payment_$TT < ./resources/mysql/paymentd.test.payment.data.sql
